
import Navbar1 from "@/components/Navbar/Navbar1/Navbar1";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar1/>
        {children}
      </body>
    </html>
  );
}
